language: java

services:
  - mysql

before_install:
  - mysql -root -e "CREATE USER 'huser'@'localhost' IDENTIFIED BY 'hpassword';"
  - mysql -root -e "GRANT ALL PRIVILEGES ON *.* TO 'huser'@'localhost' WITH GRANT OPTION; FLUSH PRIVILEGES;"
  - mysql mysql -u huser -phpassword -h localhost < src/main/resources/dbo.sql